import { useEffect, useState } from 'react'
import { supabase } from '../../lib/supabase.js'
import { printHtml, formatMoney } from '../lib/print.js'
import {
  PageHeader,
  Card,
  Button,
  EmptyState,
  currency,
} from '../components/ui.jsx'

// Company details shown on printed documents. Edit as needed.
const COMPANY = {
  name: 'JKCanopy',
  tagline: 'Arabic Canopy Rental',
  area: 'Kluang, Johor, Malaysia',
  phone: '+60 17-779 9290',
}

export default function Quotations() {
  const [rows, setRows] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  async function load() {
    setLoading(true)
    // Join quotation with its booking for customer details.
    const { data, error } = await supabase
      .from('quotations')
      .select('*, booking:bookings(*)')
      .order('created_at', { ascending: false })
    if (error) setError(error.message)
    else setRows(data ?? [])
    setLoading(false)
  }

  useEffect(() => {
    load()
  }, [])

  function printQuotation(q) {
    const b = q.booking || {}
    const depositPaid = Number(b.deposit_paid || 0)
    const balanceDue = Math.max(0, Number(q.total || 0) - depositPaid)
    const lineRows = (q.line_items || [])
      .map(
        (li) => `<tr>
          <td>${li.name}</td>
          <td class="num">${li.qty}</td>
          <td class="num">${formatMoney(li.unit_price)}</td>
          <td class="num">${formatMoney(li.amount)}</td>
        </tr>`,
      )
      .join('')

    const body = `
      <div class="brand">
        <h1>JK<span class="gold">Canopy</span></h1>
      </div>
      <div class="muted">${COMPANY.tagline} &middot; ${COMPANY.area} &middot; ${COMPANY.phone}</div>

      <div class="box">
        <div class="row">
          <div>
            <div class="muted">Quotation for</div>
            <div><strong>${b.customer_name ?? ''}</strong></div>
            <div class="muted">${b.phone ?? ''}</div>
            <div class="muted">${b.address ?? ''}</div>
          </div>
          <div style="text-align:right">
            <div class="muted">Booking No.</div>
            <div><strong>${b.booking_no ?? ''}</strong></div>
            <div class="muted">Event Date: ${b.event_date ?? '-'}</div>
            <div class="muted">Theme: ${b.theme_colour ?? '-'} / Canopy: ${b.canopy_colour ?? '-'}</div>
          </div>
        </div>
      </div>

      <table>
        <thead>
          <tr>
            <th>Item</th><th class="num">Qty</th><th class="num">Unit Price</th><th class="num">Amount</th>
          </tr>
        </thead>
        <tbody>${lineRows}</tbody>
        <tfoot>
          <tr>
            <td colspan="3" class="num">Total</td>
            <td class="num total">${formatMoney(q.total)}</td>
          </tr>
          <tr>
            <td colspan="3" class="num">Deposit</td>
            <td class="num">${formatMoney(depositPaid)}</td>
          </tr>
          <tr>
            <td colspan="3" class="num total">Balance</td>
            <td class="num total">${formatMoney(balanceDue)}</td>
          </tr>
        </tfoot>
      </table>

      <div class="footer">
        This quotation is generated by ${COMPANY.name}. Prices are subject to confirmation.
        Thank you / Terima kasih.
      </div>
    `
    printHtml(`Quotation ${b.booking_no ?? ''}`, body)
  }

  return (
    <div>
      <PageHeader title="Quotations" subtitle="Quotation list - print or save as PDF" />

      {error && <p className="mb-4 rounded-lg bg-red-100 px-3 py-2 text-sm text-red-700">{error}</p>}

      {loading ? (
        <p className="text-sm text-canopy/60">Loading...</p>
      ) : rows.length === 0 ? (
        <EmptyState>No quotations yet. They are created when you confirm a booking.</EmptyState>
      ) : (
        <Card>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-canopy/10 text-left text-canopy/70">
                  <th className="py-2 pr-3 font-medium">Booking No.</th>
                  <th className="py-2 pr-3 font-medium">Customer</th>
                  <th className="py-2 pr-3 font-medium">Event Date</th>
                  <th className="py-2 pr-3 font-medium">Total</th>
                  <th className="py-2 font-medium"></th>
                </tr>
              </thead>
              <tbody>
                {rows.map((q) => (
                  <tr key={q.id} className="border-b border-canopy/5">
                    <td className="py-2 pr-3 font-medium text-canopy-dark">
                      {q.booking?.booking_no ?? '-'}
                    </td>
                    <td className="py-2 pr-3 text-canopy-dark">{q.booking?.customer_name ?? '-'}</td>
                    <td className="py-2 pr-3 text-canopy/70">{q.booking?.event_date ?? '-'}</td>
                    <td className="py-2 pr-3">{currency(q.total)}</td>
                    <td className="py-2 text-right">
                      <Button variant="outline" onClick={() => printQuotation(q)}>
                        Print / PDF
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      )}
    </div>
  )
}
